# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

_sym_db = _symbol_database.Default()


# --- Enums ---

class _LogLevel:
    """LogLevel enum"""
    _VALUES = {
        'DEBUG': 0,
        'INFO': 1,
        'WARNING': 2,
        'ERROR': 3,
        'CRITICAL': 4,
    }

DEBUG = 0
INFO = 1
WARNING = 2
ERROR = 3
CRITICAL = 4

LogLevel = enum_type_wrapper.EnumTypeWrapper(_LogLevel)


# --- Descriptors ---

DESCRIPTOR = _descriptor.FileDescriptor(
    name='agent.proto',
    package='agent',
    syntax='proto3',
)


# --- Messages ---

class StartRequest(_message.Message):
    """StartRequest message"""

    DESCRIPTOR = _descriptor.Descriptor(
        name='StartRequest',
        full_name='agent.StartRequest',
        filename='agent.proto',
        containing_type=None,
        fields=[
            _descriptor.FieldDescriptor(
                name='project_path', full_name='agent.StartRequest.project_path',
                index=0, number=1, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='goals', full_name='agent.StartRequest.goals',
                index=1, number=2, type=11, cpp_type=10, label=3,
                has_default_value=False, default_value=[],
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='auto_apply', full_name='agent.StartRequest.auto_apply',
                index=2, number=3, type=8, cpp_type=7, label=1,
                has_default_value=False, default_value=False,
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='config', full_name='agent.StartRequest.config',
                index=3, number=4, type=11, cpp_type=10, label=1,
                has_default_value=False, default_value=None,
                containing_type=None, is_extension=False, extension_scope=None
            ),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[
            _descriptor.OneofDescriptor(
                name='config', full_name='agent.StartRequest.config',
                index=0, containing_type=None, fields=[]
            ),
        ],
    )

    # Fields
    project_path = _property(_descriptor.FieldDescriptor.name_to_number('project_path'))
    goals = _property(_descriptor.FieldDescriptor.name_to_number('goals'))
    auto_apply = _property(_descriptor.FieldDescriptor.name_to_number('auto_apply'))
    config = _property(_descriptor.FieldDescriptor.name_to_number('config'))


class LoopResponse(_message.Message):
    """LoopResponse message"""

    DESCRIPTOR = _descriptor.Descriptor(
        name='LoopResponse',
        full_name='agent.LoopResponse',
        filename='agent.proto',
        containing_type=None,
        fields=[
            _descriptor.FieldDescriptor(
                name='success', full_name='agent.LoopResponse.success',
                index=0, number=1, type=8, cpp_type=7, label=1,
                has_default_value=False, default_value=False,
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='loop_id', full_name='agent.LoopResponse.loop_id',
                index=1, number=2, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='message', full_name='agent.LoopResponse.message',
                index=2, number=3, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[],
    )

    success = _property(_descriptor.FieldDescriptor.name_to_number('success'))
    loop_id = _property(_descriptor.FieldDescriptor.name_to_number('loop_id'))
    message = _property(_descriptor.FieldDescriptor.name_to_number('message'))


class StopRequest(_message.Message):
    """StopRequest message"""

    DESCRIPTOR = _descriptor.Descriptor(
        name='StopRequest',
        full_name='agent.StopRequest',
        filename='agent.proto',
        containing_type=None,
        fields=[
            _descriptor.FieldDescriptor(
                name='loop_id', full_name='agent.StopRequest.loop_id',
                index=0, number=1, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[],
    )

    loop_id = _property(_descriptor.FieldDescriptor.name_to_number('loop_id'))


class StatusRequest(_message.Message):
    """StatusRequest message"""

    DESCRIPTOR = _descriptor.Descriptor(
        name='StatusRequest',
        full_name='agent.StatusRequest',
        filename='agent.proto',
        containing_type=None,
        fields=[
            _descriptor.FieldDescriptor(
                name='loop_id', full_name='agent.StatusRequest.loop_id',
                index=0, number=1, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[],
    )

    loop_id = _property(_descriptor.FieldDescriptor.name_to_number('loop_id'))


class GoalStatus(_message.Message):
    """GoalStatus message"""

    DESCRIPTOR = _descriptor.Descriptor(
        name='GoalStatus',
        full_name='agent.GoalStatus',
        filename='agent.proto',
        containing_type=None,
        fields=[
            _descriptor.FieldDescriptor(
                name='name', full_name='agent.GoalStatus.name',
                index=0, number=1, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='progress', full_name='agent.GoalStatus.progress',
                index=1, number=2, type=1, cpp_type=5, label=1,
                has_default_value=False, default_value=0.0,
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='completed', full_name='agent.GoalStatus.completed',
                index=2, number=3, type=8, cpp_type=7, label=1,
                has_default_value=False, default_value=False,
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='category', full_name='agent.GoalStatus.category',
                index=3, number=4, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[],
    )

    name = _property(_descriptor.FieldDescriptor.name_to_number('name'))
    progress = _property(_descriptor.FieldDescriptor.name_to_number('progress'))
    completed = _property(_descriptor.FieldDescriptor.name_to_number('completed'))
    category = _property(_descriptor.FieldDescriptor.name_to_number('category'))


class StatusResponse(_message.Message):
    """StatusResponse message"""

    DESCRIPTOR = _descriptor.Descriptor(
        name='StatusResponse',
        full_name='agent.StatusResponse',
        filename='agent.proto',
        containing_type=None,
        fields=[
            _descriptor.FieldDescriptor(
                name='loop_id', full_name='agent.StatusResponse.loop_id',
                index=0, number=1, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='running', full_name='agent.StatusResponse.running',
                index=1, number=2, type=8, cpp_type=7, label=1,
                has_default_value=False, default_value=False,
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='iteration', full_name='agent.StatusResponse.iteration',
                index=2, number=3, type=5, cpp_type=3, label=1,
                has_default_value=False, default_value=0,
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='current_phase', full_name='agent.StatusResponse.current_phase',
                index=3, number=4, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='goals', full_name='agent.StatusResponse.goals',
                index=4, number=5, type=11, cpp_type=10, label=3,
                has_default_value=False, default_value=[],
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='started_at', full_name='agent.StatusResponse.started_at',
                index=5, number=6, type=3, cpp_type=3, label=1,
                has_default_value=False, default_value=0,
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='last_activity', full_name='agent.StatusResponse.last_activity',
                index=6, number=7, type=3, cpp_type=3, label=1,
                has_default_value=False, default_value=0,
                containing_type=None, is_extension=False, extension_scope=None
            ),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[],
    )

    loop_id = _property(_descriptor.FieldDescriptor.name_to_number('loop_id'))
    running = _property(_descriptor.FieldDescriptor.name_to_number('running'))
    iteration = _property(_descriptor.FieldDescriptor.name_to_number('iteration'))
    current_phase = _property(_descriptor.FieldDescriptor.name_to_number('current_phase'))
    goals = _property(_descriptor.FieldDescriptor.name_to_number('goals'))
    started_at = _property(_descriptor.FieldDescriptor.name_to_number('started_at'))
    last_activity = _property(_descriptor.FieldDescriptor.name_to_number('last_activity'))


class Goal(_message.Message):
    """Goal message"""

    DESCRIPTOR = _descriptor.Descriptor(
        name='Goal',
        full_name='agent.Goal',
        filename='agent.proto',
        containing_type=None,
        fields=[
            _descriptor.FieldDescriptor(
                name='name', full_name='agent.Goal.name',
                index=0, number=1, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='description', full_name='agent.Goal.description',
                index=1, number=2, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='category', full_name='agent.Goal.category',
                index=2, number=3, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='target_value', full_name='agent.Goal.target_value',
                index=3, number=4, type=1, cpp_type=5, label=1,
                has_default_value=False, default_value=0.0,
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='current_value', full_name='agent.Goal.current_value',
                index=4, number=5, type=1, cpp_type=5, label=1,
                has_default_value=False, default_value=0.0,
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='unit', full_name='agent.Goal.unit',
                index=5, number=6, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='metadata', full_name='agent.Goal.metadata',
                index=6, number=7, type=11, cpp_type=10, label=1,
                has_default_value=False, default_value=None,
                containing_type=None, is_extension=False, extension_scope=None
            ),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[],
    )

    name = _property(_descriptor.FieldDescriptor.name_to_number('name'))
    description = _property(_descriptor.FieldDescriptor.name_to_number('description'))
    category = _property(_descriptor.FieldDescriptor.name_to_number('category'))
    target_value = _property(_descriptor.FieldDescriptor.name_to_number('target_value'))
    current_value = _property(_descriptor.FieldDescriptor.name_to_number('current_value'))
    unit = _property(_descriptor.FieldDescriptor.name_to_number('unit'))
    metadata = _property(_descriptor.FieldDescriptor.name_to_number('metadata'))


class GoalRequest(_message.Message):
    """GoalRequest message"""

    DESCRIPTOR = _descriptor.Descriptor(
        name='GoalRequest',
        full_name='agent.GoalRequest',
        filename='agent.proto',
        containing_type=None,
        fields=[
            _descriptor.FieldDescriptor(
                name='loop_id', full_name='agent.GoalRequest.loop_id',
                index=0, number=1, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='goal', full_name='agent.GoalRequest.goal',
                index=1, number=2, type=11, cpp_type=10, label=1,
                has_default_value=False, default_value=None,
                containing_type=None, is_extension=False, extension_scope=None
            ),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[],
    )

    loop_id = _property(_descriptor.FieldDescriptor.name_to_number('loop_id'))
    goal = _property(_descriptor.FieldDescriptor.name_to_number('goal'))


class GoalResponse(_message.Message):
    """GoalResponse message"""

    DESCRIPTOR = _descriptor.Descriptor(
        name='GoalResponse',
        full_name='agent.GoalResponse',
        filename='agent.proto',
        containing_type=None,
        fields=[
            _descriptor.FieldDescriptor(
                name='success', full_name='agent.GoalResponse.success',
                index=0, number=1, type=8, cpp_type=7, label=1,
                has_default_value=False, default_value=False,
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='message', full_name='agent.GoalResponse.message',
                index=1, number=2, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='goal', full_name='agent.GoalResponse.goal',
                index=2, number=3, type=11, cpp_type=10, label=1,
                has_default_value=False, default_value=None,
                containing_type=None, is_extension=False, extension_scope=None
            ),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[],
    )

    success = _property(_descriptor.FieldDescriptor.name_to_number('success'))
    message = _property(_descriptor.FieldDescriptor.name_to_number('message'))
    goal = _property(_descriptor.FieldDescriptor.name_to_number('goal'))


class Issue(_message.Message):
    """Issue message"""

    DESCRIPTOR = _descriptor.Descriptor(
        name='Issue',
        full_name='agent.Issue',
        filename='agent.proto',
        containing_type=None,
        fields=[
            _descriptor.FieldDescriptor(
                name='title', full_name='agent.Issue.title',
                index=0, number=1, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='description', full_name='agent.Issue.description',
                index=1, number=2, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='severity', full_name='agent.Issue.severity',
                index=2, number=3, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='category', full_name='agent.Issue.category',
                index=3, number=4, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='metadata', full_name='agent.Issue.metadata',
                index=4, number=5, type=11, cpp_type=10, label=1,
                has_default_value=False, default_value=None,
                containing_type=None, is_extension=False, extension_scope=None
            ),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[],
    )

    title = _property(_descriptor.FieldDescriptor.name_to_number('title'))
    description = _property(_descriptor.FieldDescriptor.name_to_number('description'))
    severity = _property(_descriptor.FieldDescriptor.name_to_number('severity'))
    category = _property(_descriptor.FieldDescriptor.name_to_number('category'))
    metadata = _property(_descriptor.FieldDescriptor.name_to_number('metadata'))


class AnalyzeRequest(_message.Message):
    """AnalyzeRequest message"""

    DESCRIPTOR = _descriptor.Descriptor(
        name='AnalyzeRequest',
        full_name='agent.AnalyzeRequest',
        filename='agent.proto',
        containing_type=None,
        fields=[
            _descriptor.FieldDescriptor(
                name='loop_id', full_name='agent.AnalyzeRequest.loop_id',
                index=0, number=1, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='focus_area', full_name='agent.AnalyzeRequest.focus_area',
                index=1, number=2, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='context', full_name='agent.AnalyzeRequest.context',
                index=2, number=3, type=11, cpp_type=10, label=1,
                has_default_value=False, default_value=None,
                containing_type=None, is_extension=False, extension_scope=None
            ),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[],
    )

    loop_id = _property(_descriptor.FieldDescriptor.name_to_number('loop_id'))
    focus_area = _property(_descriptor.FieldDescriptor.name_to_number('focus_area'))
    context = _property(_descriptor.FieldDescriptor.name_to_number('context'))


class AnalyzeResponse(_message.Message):
    """AnalyzeResponse message"""

    DESCRIPTOR = _descriptor.Descriptor(
        name='AnalyzeResponse',
        full_name='agent.AnalyzeResponse',
        filename='agent.proto',
        containing_type=None,
        fields=[
            _descriptor.FieldDescriptor(
                name='success', full_name='agent.AnalyzeResponse.success',
                index=0, number=1, type=8, cpp_type=7, label=1,
                has_default_value=False, default_value=False,
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='analysis', full_name='agent.AnalyzeResponse.analysis',
                index=1, number=2, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='recommendations', full_name='agent.AnalyzeResponse.recommendations',
                index=2, number=3, type=9, cpp_type=9, label=3,
                has_default_value=False, default_value=[],
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='issues', full_name='agent.AnalyzeResponse.issues',
                index=3, number=4, type=11, cpp_type=10, label=3,
                has_default_value=False, default_value=[],
                containing_type=None, is_extension=False, extension_scope=None
            ),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[],
    )

    success = _property(_descriptor.FieldDescriptor.name_to_number('success'))
    analysis = _property(_descriptor.FieldDescriptor.name_to_number('analysis'))
    recommendations = _property(_descriptor.FieldDescriptor.name_to_number('recommendations'))
    issues = _property(_descriptor.FieldDescriptor.name_to_number('issues'))


class ReviewRequest(_message.Message):
    """ReviewRequest message"""

    DESCRIPTOR = _descriptor.Descriptor(
        name='ReviewRequest',
        full_name='agent.ReviewRequest',
        filename='agent.proto',
        containing_type=None,
        fields=[
            _descriptor.FieldDescriptor(
                name='loop_id', full_name='agent.ReviewRequest.loop_id',
                index=0, number=1, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='iteration_id', full_name='agent.ReviewRequest.iteration_id',
                index=1, number=2, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='decision', full_name='agent.ReviewRequest.decision',
                index=2, number=3, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='feedback', full_name='agent.ReviewRequest.feedback',
                index=3, number=4, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[],
    )

    loop_id = _property(_descriptor.FieldDescriptor.name_to_number('loop_id'))
    iteration_id = _property(_descriptor.FieldDescriptor.name_to_number('iteration_id'))
    decision = _property(_descriptor.FieldDescriptor.name_to_number('decision'))
    feedback = _property(_descriptor.FieldDescriptor.name_to_number('feedback'))


class ReviewResponse(_message.Message):
    """ReviewResponse message"""

    DESCRIPTOR = _descriptor.Descriptor(
        name='ReviewResponse',
        full_name='agent.ReviewResponse',
        filename='agent.proto',
        containing_type=None,
        fields=[
            _descriptor.FieldDescriptor(
                name='success', full_name='agent.ReviewResponse.success',
                index=0, number=1, type=8, cpp_type=7, label=1,
                has_default_value=False, default_value=False,
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='message', full_name='agent.ReviewResponse.message',
                index=1, number=2, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='applied', full_name='agent.ReviewResponse.applied',
                index=2, number=3, type=8, cpp_type=7, label=1,
                has_default_value=False, default_value=False,
                containing_type=None, is_extension=False, extension_scope=None
            ),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[],
    )

    success = _property(_descriptor.FieldDescriptor.name_to_number('success'))
    message = _property(_descriptor.FieldDescriptor.name_to_number('message'))
    applied = _property(_descriptor.FieldDescriptor.name_to_number('applied'))


class Metric(_message.Message):
    """Metric message"""

    DESCRIPTOR = _descriptor.Descriptor(
        name='Metric',
        full_name='agent.Metric',
        filename='agent.proto',
        containing_type=None,
        fields=[
            _descriptor.FieldDescriptor(
                name='name', full_name='agent.Metric.name',
                index=0, number=1, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='value', full_name='agent.Metric.value',
                index=1, number=2, type=1, cpp_type=5, label=1,
                has_default_value=False, default_value=0.0,
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='unit', full_name='agent.Metric.unit',
                index=2, number=3, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='timestamp', full_name='agent.Metric.timestamp',
                index=3, number=4, type=3, cpp_type=3, label=1,
                has_default_value=False, default_value=0,
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='labels', full_name='agent.Metric.labels',
                index=4, number=5, type=11, cpp_type=10, label=1,
                has_default_value=False, default_value=None,
                containing_type=None, is_extension=False, extension_scope=None
            ),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[],
    )

    name = _property(_descriptor.FieldDescriptor.name_to_number('name'))
    value = _property(_descriptor.FieldDescriptor.name_to_number('value'))
    unit = _property(_descriptor.FieldDescriptor.name_to_number('unit'))
    timestamp = _property(_descriptor.FieldDescriptor.name_to_number('timestamp'))
    labels = _property(_descriptor.FieldDescriptor.name_to_number('labels'))


class MetricsRequest(_message.Message):
    """MetricsRequest message"""

    DESCRIPTOR = _descriptor.Descriptor(
        name='MetricsRequest',
        full_name='agent.MetricsRequest',
        filename='agent.proto',
        containing_type=None,
        fields=[
            _descriptor.FieldDescriptor(
                name='loop_id', full_name='agent.MetricsRequest.loop_id',
                index=0, number=1, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='metric_names', full_name='agent.MetricsRequest.metric_names',
                index=1, number=2, type=9, cpp_type=9, label=3,
                has_default_value=False, default_value=[],
                containing_type=None, is_extension=False, extension_scope=None
            ),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[],
    )

    loop_id = _property(_descriptor.FieldDescriptor.name_to_number('loop_id'))
    metric_names = _property(_descriptor.FieldDescriptor.name_to_number('metric_names'))


class MetricsResponse(_message.Message):
    """MetricsResponse message"""

    DESCRIPTOR = _descriptor.Descriptor(
        name='MetricsResponse',
        full_name='agent.MetricsResponse',
        filename='agent.proto',
        containing_type=None,
        fields=[
            _descriptor.FieldDescriptor(
                name='metrics', full_name='agent.MetricsResponse.metrics',
                index=0, number=1, type=11, cpp_type=10, label=3,
                has_default_value=False, default_value=[],
                containing_type=None, is_extension=False, extension_scope=None
            ),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[],
    )

    metrics = _property(_descriptor.FieldDescriptor.name_to_number('metrics'))


class LogRequest(_message.Message):
    """LogRequest message"""

    DESCRIPTOR = _descriptor.Descriptor(
        name='LogRequest',
        full_name='agent.LogRequest',
        filename='agent.proto',
        containing_type=None,
        fields=[
            _descriptor.FieldDescriptor(
                name='loop_id', full_name='agent.LogRequest.loop_id',
                index=0, number=1, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='since', full_name='agent.LogRequest.since',
                index=1, number=2, type=3, cpp_type=3, label=1,
                has_default_value=False, default_value=0,
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='level', full_name='agent.LogRequest.level',
                index=2, number=3, type=14, cpp_type=2, label=1,
                has_default_value=False, default_value=0,
                containing_type=None, is_extension=False, extension_scope=None
            ),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[],
    )

    loop_id = _property(_descriptor.FieldDescriptor.name_to_number('loop_id'))
    since = _property(_descriptor.FieldDescriptor.name_to_number('since'))
    level = _property(_descriptor.FieldDescriptor.name_to_number('level'))


class LogEvent(_message.Message):
    """LogEvent message"""

    DESCRIPTOR = _descriptor.Descriptor(
        name='LogEvent',
        full_name='agent.LogEvent',
        filename='agent.proto',
        containing_type=None,
        fields=[
            _descriptor.FieldDescriptor(
                name='timestamp', full_name='agent.LogEvent.timestamp',
                index=0, number=1, type=3, cpp_type=3, label=1,
                has_default_value=False, default_value=0,
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='level', full_name='agent.LogEvent.level',
                index=1, number=2, type=14, cpp_type=2, label=1,
                has_default_value=False, default_value=0,
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='message', full_name='agent.LogEvent.message',
                index=2, number=3, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='metadata', full_name='agent.LogEvent.metadata',
                index=3, number=4, type=11, cpp_type=10, label=1,
                has_default_value=False, default_value=None,
                containing_type=None, is_extension=False, extension_scope=None
            ),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[],
    )

    timestamp = _property(_descriptor.FieldDescriptor.name_to_number('timestamp'))
    level = _property(_descriptor.FieldDescriptor.name_to_number('level'))
    message = _property(_descriptor.FieldDescriptor.name_to_number('message'))
    metadata = _property(_descriptor.FieldDescriptor.name_to_number('metadata'))


class LooperConfig(_message.Message):
    """LooperConfig message"""

    DESCRIPTOR = _descriptor.Descriptor(
        name='LooperConfig',
        full_name='agent.LooperConfig',
        filename='agent.proto',
        containing_type=None,
        fields=[
            _descriptor.FieldDescriptor(
                name='max_iterations', full_name='agent.LooperConfig.max_iterations',
                index=0, number=1, type=5, cpp_type=3, label=1,
                has_default_value=False, default_value=0,
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='iteration_interval', full_name='agent.LooperConfig.iteration_interval',
                index=1, number=2, type=5, cpp_type=3, label=1,
                has_default_value=False, default_value=0,
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='auto_apply', full_name='agent.LooperConfig.auto_apply',
                index=2, number=3, type=8, cpp_type=7, label=1,
                has_default_value=False, default_value=False,
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='model', full_name='agent.LooperConfig.model',
                index=3, number=4, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value="",
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='temperature', full_name='agent.LooperConfig.temperature',
                index=4, number=5, type=1, cpp_type=5, label=1,
                has_default_value=False, default_value=0.0,
                containing_type=None, is_extension=False, extension_scope=None
            ),
            _descriptor.FieldDescriptor(
                name='max_tokens', full_name='agent.LooperConfig.max_tokens',
                index=5, number=6, type=5, cpp_type=3, label=1,
                has_default_value=False, default_value=0,
                containing_type=None, is_extension=False, extension_scope=None
            ),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[],
    )

    max_iterations = _property(_descriptor.FieldDescriptor.name_to_number('max_iterations'))
    iteration_interval = _property(_descriptor.FieldDescriptor.name_to_number('iteration_interval'))
    auto_apply = _property(_descriptor.FieldDescriptor.name_to_number('auto_apply'))
    model = _property(_descriptor.FieldDescriptor.name_to_number('model'))
    temperature = _property(_descriptor.FieldDescriptor.name_to_number('temperature'))
    max_tokens = _property(_descriptor.FieldDescriptor.name_to_number('max_tokens'))


# Register all messages
_sym_db.RegisterMessage(StartRequest)
_sym_db.RegisterMessage(LoopResponse)
_sym_db.RegisterMessage(StopRequest)
_sym_db.RegisterMessage(StatusRequest)
_sym_db.RegisterMessage(GoalStatus)
_sym_db.RegisterMessage(StatusResponse)
_sym_db.RegisterMessage(Goal)
_sym_db.RegisterMessage(GoalRequest)
_sym_db.RegisterMessage(GoalResponse)
_sym_db.RegisterMessage(Issue)
_sym_db.RegisterMessage(AnalyzeRequest)
_sym_db.RegisterMessage(AnalyzeResponse)
_sym_db.RegisterMessage(ReviewRequest)
_sym_db.RegisterMessage(ReviewResponse)
_sym_db.RegisterMessage(Metric)
_sym_db.RegisterMessage(MetricsRequest)
_sym_db.RegisterMessage(MetricsResponse)
_sym_db.RegisterMessage(LogRequest)
_sym_db.RegisterMessage(LogEvent)
_sym_db.RegisterMessage(LooperConfig)
