# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto
"""Agent service protocol buffers for GraphWiz-XR."""

from .agent_pb2 import *
from .agent_pb2_grpc import *

__all__ = [
    # Messages
    'StartRequest',
    'StopRequest',
    'LoopResponse',
    'StatusRequest',
    'StatusResponse',
    'GoalStatus',
    'GoalRequest',
    'Goal',
    'GoalResponse',
    'AnalyzeRequest',
    'AnalyzeResponse',
    'Issue',
    'ReviewRequest',
    'ReviewResponse',
    'MetricsRequest',
    'MetricsResponse',
    'Metric',
    'LogRequest',
    'LogEvent',
    'LooperConfig',
    # Enums
    'LogLevel',
    # Services
    'AgentLooper',
    'AgentLooperServicer',
    'add_AgentLooperServicer_to_server',
]
