# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import agent_pb2 as agent__pb2


class AgentLooperStub(object):
    """Agent Looper service for continuous optimization"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartLoop = channel.unary_unary(
            '/agent.AgentLooper/StartLoop',
            request_serializer=agent__pb2.StartRequest.SerializeToString,
            response_deserializer=agent__pb2.LoopResponse.FromString,
        )
        self.StopLoop = channel.unary_unary(
            '/agent.AgentLooper/StopLoop',
            request_serializer=agent__pb2.StopRequest.SerializeToString,
            response_deserializer=agent__pb2.LoopResponse.FromString,
        )
        self.GetStatus = channel.unary_unary(
            '/agent.AgentLooper/GetStatus',
            request_serializer=agent__pb2.StatusRequest.SerializeToString,
            response_deserializer=agent__pb2.StatusResponse.FromString,
        )
        self.SubmitGoal = channel.unary_unary(
            '/agent.AgentLooper/SubmitGoal',
            request_serializer=agent__pb2.GoalRequest.SerializeToString,
            response_deserializer=agent__pb2.GoalResponse.FromString,
        )
        self.Analyze = channel.unary_unary(
            '/agent.AgentLooper/Analyze',
            request_serializer=agent__pb2.AnalyzeRequest.SerializeToString,
            response_deserializer=agent__pb2.AnalyzeResponse.FromString,
        )
        self.ReviewChanges = channel.unary_unary(
            '/agent.AgentLooper/ReviewChanges',
            request_serializer=agent__pb2.ReviewRequest.SerializeToString,
            response_deserializer=agent__pb2.ReviewResponse.FromString,
        )
        self.GetMetrics = channel.unary_unary(
            '/agent.AgentLooper/GetMetrics',
            request_serializer=agent__pb2.MetricsRequest.SerializeToString,
            response_deserializer=agent__pb2.MetricsResponse.FromString,
        )
        self.StreamLogs = channel.unary_stream(
            '/agent.AgentLooper/StreamLogs',
            request_serializer=agent__pb2.LogRequest.SerializeToString,
            response_deserializer=agent__pb2.LogEvent.FromString,
        )


class AgentLooperServicer(object):
    """Agent Looper service for continuous optimization"""

    def StartLoop(self, request, context):
        """Start optimization loop"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopLoop(self, request, context):
        """Stop optimization loop"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get current status"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitGoal(self, request, context):
        """Submit optimization goal"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Analyze(self, request, context):
        """Request immediate analysis"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReviewChanges(self, request, context):
        """Approve/reject changes"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Get metrics"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLogs(self, request, context):
        """Stream log events"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentLooperServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'StartLoop': grpc.unary_rpc_method_handler(
            servicer.StartLoop,
            request_deserializer=agent__pb2.StartRequest.FromString,
            response_serializer=agent__pb2.LoopResponse.SerializeToString,
        ),
        'StopLoop': grpc.unary_rpc_method_handler(
            servicer.StopLoop,
            request_deserializer=agent__pb2.StopRequest.FromString,
            response_serializer=agent__pb2.LoopResponse.SerializeToString,
        ),
        'GetStatus': grpc.unary_rpc_method_handler(
            servicer.GetStatus,
            request_deserializer=agent__pb2.StatusRequest.FromString,
            response_serializer=agent__pb2.StatusResponse.SerializeToString,
        ),
        'SubmitGoal': grpc.unary_rpc_method_handler(
            servicer.SubmitGoal,
            request_deserializer=agent__pb2.GoalRequest.FromString,
            response_serializer=agent__pb2.GoalResponse.SerializeToString,
        ),
        'Analyze': grpc.unary_rpc_method_handler(
            servicer.Analyze,
            request_deserializer=agent__pb2.AnalyzeRequest.FromString,
            response_serializer=agent__pb2.AnalyzeResponse.SerializeToString,
        ),
        'ReviewChanges': grpc.unary_rpc_method_handler(
            servicer.ReviewChanges,
            request_deserializer=agent__pb2.ReviewRequest.FromString,
            response_serializer=agent__pb2.ReviewResponse.SerializeToString,
        ),
        'GetMetrics': grpc.unary_rpc_method_handler(
            servicer.GetMetrics,
            request_deserializer=agent__pb2.MetricsRequest.FromString,
            response_serializer=agent__pb2.MetricsResponse.SerializeToString,
        ),
        'StreamLogs': grpc.stream_rpc_method_handler(
            servicer.StreamLogs,
            request_deserializer=agent__pb2.LogRequest.FromString,
            response_serializer=agent__pb2.LogEvent.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'agent.AgentLooper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class AgentLooper(object):
    """Agent Looper service for continuous optimization"""

    @staticmethod
    def StartLoop(request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentLooper/StartLoop',
            agent__pb2.StartRequest.SerializeToString,
            agent__pb2.LoopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def StopLoop(request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentLooper/StopLoop',
            agent__pb2.StopRequest.SerializeToString,
            agent__pb2.LoopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetStatus(request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentLooper/GetStatus',
            agent__pb2.StatusRequest.SerializeToString,
            agent__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def SubmitGoal(request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentLooper/SubmitGoal',
            agent__pb2.GoalRequest.SerializeToString,
            agent__pb2.GoalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Analyze(request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentLooper/Analyze',
            agent__pb2.AnalyzeRequest.SerializeToString,
            agent__pb2.AnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ReviewChanges(request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentLooper/ReviewChanges',
            agent__pb2.ReviewRequest.SerializeToString,
            agent__pb2.ReviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetMetrics(request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentLooper/GetMetrics',
            agent__pb2.MetricsRequest.SerializeToString,
            agent__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def StreamLogs(request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agent.AgentLooper/StreamLogs',
            agent__pb2.LogRequest.SerializeToString,
            agent__pb2.LogEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
