import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/**
 * 3D Avatar Preview Component
 */
import { Cylinder, Sphere, Box, Cone } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { useRef } from 'react';
export function AvatarPreview({ config, animate = true }) {
    const groupRef = useRef(null);
    // Gentle rotation animation
    useFrame((state) => {
        if (animate && groupRef.current) {
            groupRef.current.rotation.y = state.clock.elapsedTime * 0.5;
        }
    });
    // Parse hex colors
    const primaryColor = config.primary_color;
    const secondaryColor = config.secondary_color;
    // Scale height (base is 1.7m)
    const scale = config.height / 1.7;
    return (_jsxs("group", { ref: groupRef, scale: scale, children: [_jsxs("mesh", { rotation: [-Math.PI / 2, 0, 0], position: [0, 0, 0], children: [_jsx("circleGeometry", { args: [0.5, 32] }), _jsx("shadowMaterial", { opacity: 0.3 })] }), config.body_type === 'human' && _jsx(HumanAvatar, { primaryColor: primaryColor, secondaryColor: secondaryColor }), config.body_type === 'robot' && _jsx(RobotAvatar, { primaryColor: primaryColor, secondaryColor: secondaryColor }), config.body_type === 'alien' && _jsx(AlienAvatar, { primaryColor: primaryColor, secondaryColor: secondaryColor }), config.body_type === 'animal' && _jsx(AnimalAvatar, { primaryColor: primaryColor, secondaryColor: secondaryColor }), config.body_type === 'abstract' && _jsx(AbstractAvatar, { primaryColor: primaryColor, secondaryColor: secondaryColor })] }));
}
// Human Avatar
function HumanAvatar({ primaryColor, secondaryColor }) {
    return (_jsxs("group", { children: [_jsx(Sphere, { position: [0, 1.6, 0], args: [0.15], castShadow: true, children: _jsx("meshStandardMaterial", { color: "#FFCC80" }) }), _jsx(Cylinder, { position: [0, 1.2, 0], args: [0.12, 0.15, 0.6, 16], castShadow: true, children: _jsx("meshStandardMaterial", { color: primaryColor }) }), _jsx(Box, { position: [-0.2, 1.2, 0], args: [0.08, 0.5, 0.08], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor }) }), _jsx(Box, { position: [0.2, 1.2, 0], args: [0.08, 0.5, 0.08], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor }) }), _jsx(Box, { position: [-0.06, 0.6, 0], args: [0.1, 0.6, 0.1], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor }) }), _jsx(Box, { position: [0.06, 0.6, 0], args: [0.1, 0.6, 0.1], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor }) }), _jsx(Sphere, { position: [-0.05, 1.63, 0.12], args: [0.02], children: _jsx("meshStandardMaterial", { color: "#000000" }) }), _jsx(Sphere, { position: [0.05, 1.63, 0.12], args: [0.02], children: _jsx("meshStandardMaterial", { color: "#000000" }) })] }));
}
// Robot Avatar
function RobotAvatar({ primaryColor, secondaryColor }) {
    return (_jsxs("group", { children: [_jsx(Box, { position: [0, 1.6, 0], args: [0.25, 0.25, 0.25], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor, metalness: 0.8, roughness: 0.2 }) }), _jsx(Cylinder, { position: [0, 1.8, 0], args: [0.02, 0.02, 0.15], castShadow: true, children: _jsx("meshStandardMaterial", { color: primaryColor }) }), _jsx(Sphere, { position: [0, 1.88, 0], args: [0.04], children: _jsx("meshStandardMaterial", { color: "#FF0000", emissive: "#FF0000", emissiveIntensity: 0.5 }) }), _jsx(Box, { position: [0, 1.1, 0], args: [0.35, 0.5, 0.25], castShadow: true, children: _jsx("meshStandardMaterial", { color: primaryColor, metalness: 0.6, roughness: 0.3 }) }), _jsx(Box, { position: [-0.25, 1.1, 0], args: [0.08, 0.5, 0.08], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor, metalness: 0.7 }) }), _jsx(Box, { position: [0.25, 1.1, 0], args: [0.08, 0.5, 0.08], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor, metalness: 0.7 }) }), _jsx(Box, { position: [-0.08, 0.5, 0], args: [0.12, 0.5, 0.12], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor, metalness: 0.7 }) }), _jsx(Box, { position: [0.08, 0.5, 0], args: [0.12, 0.5, 0.12], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor, metalness: 0.7 }) }), _jsx(Sphere, { position: [-0.08, 1.63, 0.13], args: [0.03], children: _jsx("meshStandardMaterial", { color: "#00FF00", emissive: "#00FF00", emissiveIntensity: 0.8 }) }), _jsx(Sphere, { position: [0.08, 1.63, 0.13], args: [0.03], children: _jsx("meshStandardMaterial", { color: "#00FF00", emissive: "#00FF00", emissiveIntensity: 0.8 }) })] }));
}
// Alien Avatar
function AlienAvatar({ primaryColor, secondaryColor }) {
    return (_jsxs("group", { children: [_jsx(Sphere, { position: [0, 1.65, 0], args: [0.2, 16, 16], castShadow: true, scale: [1, 1.3, 1], children: _jsx("meshStandardMaterial", { color: secondaryColor }) }), _jsx(Cylinder, { position: [0, 1.1, 0], args: [0.08, 0.12, 0.5, 16], castShadow: true, children: _jsx("meshStandardMaterial", { color: primaryColor }) }), _jsx(Box, { position: [-0.18, 1.15, 0], args: [0.06, 0.6, 0.06], rotation: [0, 0, 0.2], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor }) }), _jsx(Box, { position: [0.18, 1.15, 0], args: [0.06, 0.6, 0.06], rotation: [0, 0, -0.2], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor }) }), _jsx(Box, { position: [-0.05, 0.55, 0], args: [0.08, 0.55, 0.08], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor }) }), _jsx(Box, { position: [0.05, 0.55, 0], args: [0.08, 0.55, 0.08], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor }) }), _jsx(Sphere, { position: [-0.08, 1.68, 0.15], args: [0.05, 16, 16], scale: [1, 1.5, 1], children: _jsx("meshStandardMaterial", { color: "#000000" }) }), _jsx(Sphere, { position: [0.08, 1.68, 0.15], args: [0.05, 16, 16], scale: [1, 1.5, 1], children: _jsx("meshStandardMaterial", { color: "#000000" }) })] }));
}
// Animal Avatar (bipedal creature)
function AnimalAvatar({ primaryColor, secondaryColor }) {
    return (_jsxs("group", { children: [_jsx(Sphere, { position: [0, 1.4, 0], args: [0.18], castShadow: true, children: _jsx("meshStandardMaterial", { color: primaryColor }) }), _jsx(Cone, { position: [-0.12, 1.55, 0], args: [0.05, 0.15, 4], rotation: [0, 0, -0.3], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor }) }), _jsx(Cone, { position: [0.12, 1.55, 0], args: [0.05, 0.15, 4], rotation: [0, 0, 0.3], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor }) }), _jsx(Sphere, { position: [0, 1.32, 0.12], args: [0.1], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor }) }), _jsx(Sphere, { position: [0, 0.9, 0], args: [0.2, 16, 16], castShadow: true, scale: [1, 1.2, 0.9], children: _jsx("meshStandardMaterial", { color: primaryColor }) }), _jsx(Sphere, { position: [-0.2, 0.9, 0], args: [0.08], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor }) }), _jsx(Sphere, { position: [0.2, 0.9, 0], args: [0.08], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor }) }), _jsx(Cylinder, { position: [-0.08, 0.4, 0], args: [0.08, 0.35, 8], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor }) }), _jsx(Cylinder, { position: [0.08, 0.4, 0], args: [0.08, 0.35, 8], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor }) }), _jsx(Cylinder, { position: [0, 0.7, -0.15], args: [0.03, 0.06, 0.3], rotation: [0.5, 0, 0], castShadow: true, children: _jsx("meshStandardMaterial", { color: primaryColor }) }), _jsx(Sphere, { position: [-0.08, 1.43, 0.12], args: [0.03], children: _jsx("meshStandardMaterial", { color: "#000000" }) }), _jsx(Sphere, { position: [0.08, 1.43, 0.12], args: [0.03], children: _jsx("meshStandardMaterial", { color: "#000000" }) })] }));
}
// Abstract Avatar (geometric shapes)
function AbstractAvatar({ primaryColor, secondaryColor }) {
    return (_jsxs("group", { children: [_jsx(Box, { position: [0, 1.2, 0], args: [0.3, 0.4, 0.3], castShadow: true, rotation: [0, 0, 0], children: _jsx("meshStandardMaterial", { color: primaryColor, emissive: primaryColor, emissiveIntensity: 0.2 }) }), _jsx(Sphere, { position: [0.2, 1.4, 0], args: [0.08], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor, emissive: secondaryColor, emissiveIntensity: 0.3 }) }), _jsx(Sphere, { position: [-0.2, 1.4, 0], args: [0.08], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor, emissive: secondaryColor, emissiveIntensity: 0.3 }) }), _jsx(Sphere, { position: [0, 1.4, 0.2], args: [0.08], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor, emissive: secondaryColor, emissiveIntensity: 0.3 }) }), _jsx(Sphere, { position: [0, 1.4, -0.2], args: [0.08], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor, emissive: secondaryColor, emissiveIntensity: 0.3 }) }), _jsx(Cylinder, { position: [0, 0.7, 0], args: [0.15, 0.2, 0.3, 6], castShadow: true, children: _jsx("meshStandardMaterial", { color: secondaryColor, metalness: 0.5 }) }), _jsx(Box, { position: [0, 1.7, 0], args: [0.15, 0.15, 0.15], castShadow: true, children: _jsx("meshStandardMaterial", { color: primaryColor, emissive: primaryColor, emissiveIntensity: 0.4 }) })] }));
}
